### ISSUE TITLE
Modify delete function

### ISSUE THREAD

**Issue by raghavprasad13** [jineetd/discourse-popup#18]
Deletion successfully deletes the previous and next topics in the current topic, however, the current topic which appears as a next or previous topic as a result of the addition of previous and next topics to the current topic remains unaltered. For instance, say the current topic is 20. We now proceed to add 4 as a previous topic and 7 as a next topic. This would result in 20 becoming a next topic for 4 and a previous topic for 7. Now say if we delete 4 as a previous topic of 20, this change is reflected in 20 as 4 is removed as a previous topic for 20. However, if we go to 4, 20 will still be listed as a next topic for 4.

**Comment by gnowgi** [comment]
One way to resolve the issue is to record only the previous topics. Even when you create a next topic to a topic, do not save the data in a separate field called next topic. Add the current topic as a previous topic to the next. If you have only one field you can ensure that the data integrity is not lost. Write function to calculate the previous and next topics. 

Let me know if this approach works?

**Comment by raghavprasad13** [comment]
@gnowgi yes sir. We'll try this and let you know
